### ISSUE TITLE
Hostname isn't correctly set when using both Ethernet and Wifi

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/printnanny-os#188]
## **Describe the bug**
>>> Maybe I missed this in the documentation, but I have a habit with my PIs of plugging in ethernet, as well as making sure WiFi is on in case I lose wired.

PrintNanny (nats in particular) seems to have issues when plugging in both. I was getting a lot of 503s, and the hostname wasn't setting right. 

Unplugged wired, rebooted, hostname shows what I chose and not getting the 503s

Original report: https://discord.com/channels/773452324692688956/783897526125199380/1060239233689866250

## **To Reproduce**
TBD

## Issue.txt
0.5.0 release

**Comment by leigh-johnson** [comment]
I'm pulling out notes from cloud-init docs, since that's the entry-point for network config.

PrintNanny uses the following `cloud.cfg`:

`/etc/cloud/cloud.cfg`
```
system_info:
   # This will affect which distro class gets used
   distro: bitsy
   network:
      renderers: ['netplan', 'network-manager', 'networkd', 'eni']
```

`/boot/network-config` is rendered by the Raspberry Pi Imager.
```
pn-v0-5:~$ cat /boot/network-config .
version: 2
wifis:
  renderer: networkd
  wlan0:
    dhcp4: true
    optional: true
    access-points:
      <redacted>
```

```
 [Cloud-init](https://launchpad.net/cloud-init) will attempt to determine which of any attached network devices is most likely to have a connection and then generate a network configuration to issue a DHCP request on that interface.

[Cloud-init](https://launchpad.net/cloud-init) runs during early boot and does not expect composed network devices (such as Bridges) to be available. [Cloud-init](https://launchpad.net/cloud-init) does not consider the following interface devices as likely ‘first’ network interfaces for fallback configuration; they are filtered out from being selected.

loopback: name=lo

Virtual Ethernet: name=veth*

Software Bridges: type=bridge

Software VLANs: type=vlan
```
